/** Map stable API error_code → i18n key under errors.* */

const KNOWN: Record<string, string> = {
  legal_required: "errors.legalRequired",
  enrollment_required: "errors.enrollmentRequired",
  onboarding_already_completed: "errors.onboardingDone",
  satellite_limit_reached: "errors.satelliteLimit",
  duplicate_exercise_same_day: "errors.duplicateExercise",
  session_immutable_after_evaluate: "errors.sessionImmutable",
  session_date_immutable: "errors.sessionDateImmutable",
  batch_too_large: "errors.batchTooLarge",
  email_not_verified: "errors.emailNotVerified",
  oauth_state_invalid: "errors.oauthState",
  unauthorized: "errors.unauthorized",
  not_found: "errors.notFound",
  nothing_to_update: "errors.nothingToUpdate",
  satellite_config_required: "errors.satelliteConfigRequired",
  satellite_config_not_found: "errors.satelliteConfigNotFound",
  satellite_config_mismatch: "errors.satelliteConfigMismatch",
  satellite_config_hash_invalid: "errors.satelliteConfigHashInvalid",
  invalid_weight_kg: "errors.invalidWeightKg",
  weight_kg_must_be_decimal_string: "errors.invalidWeightKg",
  weight_kg_too_many_places: "errors.invalidWeightKg",
  empty_set: "errors.emptySet",
  invalid_satellite_rules: "errors.invalidSatelliteRules",
  invalid_active_metrics: "errors.invalidActiveMetrics",
  invalid_step_count: "errors.invalidStepCount",
  steps_required: "errors.stepsRequired",
  stage1_goal_only_one_step: "errors.stage1GoalOnlyOneStep",
  goal_only_requires_one_step: "errors.goalOnlyRequiresOneStep",
  steps_mode_requires_2_to_5: "errors.stepsModeRequires2To5",
  satellite_step_topology_locked: "errors.satelliteTopologyLocked",
  conflict_lost: "errors.conflictLost",
  revision_jump: "errors.revisionJump",
  bilateral_not_allowed_when_require_both_sides: "errors.bilateralNotAllowed",
  recommendation_stale: "errors.recommendationStale",
  recommendation_not_pending: "errors.recommendationNotPending",
  override_rate_limited: "errors.overrideRateLimited",
  invalid_step: "errors.invalidStep",
  related_outcome_not_found: "errors.relatedOutcomeNotFound",
  related_outcome_not_adjustable: "errors.relatedOutcomeNotAdjustable",
  related_outcome_cc_unsupported: "errors.relatedOutcomeCcUnsupported",
};

export function errorCodeToI18nKey(errorCode: string): string {
  return KNOWN[errorCode] ?? "errors.generic";
}
